---
--- Generated by Luanalysis
--- Created by lyrthras.
--- DateTime: 24/08/2021 9:26 PM
---

--- All sorts of activeitems
---@class Activeitem : Item
---@field tier number
---@field element string
---@field twoHanded boolean

-- TODO

local base = require "readers.item".read

local function read(path, json)
  ---@type Activeitem
  local item = base(path, json)

  return item
end

return {read = read}
