---
--- Generated by Luanalysis
--- Created by lyrthras.
--- DateTime: 24/08/2021 3:53 AM
---

--- Augments, collars, lures
---@class Augment : Item
---@field augmentType string
---@field augmentName string
---@field effects (table|string)[]    @ [ "ghostlyglow", {"stat" : "wetImmunity", "amount" : 1.0 } ]

local log = require "log"
local base = require "readers.item".read

local function read(path, json)
  ---@type Augment
  local item = base(path, json)

  if json.augment then
    item.augmentName = json.augment.displayName
    item.augmentType = "augment"
    item.effects = json.augment.effects
  elseif json.collar then
    item.augmentName = json.collar.displayName
    item.augmentType = "collar"
    item.effects = json.collar.effects
  elseif json.lureName then
    item.augmentName = json.augment.lureName
    item.augmentType = "lure"
    item.effects = {}
  else
    log.warn("unknown augment type for %s, ignoring.", path)
    return nil
  end

  if next(item.effects) == nil then
    item.effects = {}
  end

  return item
end

return {read = read}
