---
--- Generated by Luanalysis
--- Created by lyrthras.
--- DateTime: 24/08/2021 6:52 PM
---

--- Consumables
---@class Consumable : Item
---@field foodValue number
---@field effects (table|string)[]

local base = require "readers.item".read

local function read(path, json)
  ---@type Consumable
  local item = base(path, json)

  item.foodValue = json.foodValue
  item.effects = json.effects[1]

  return item
end

return {read = read}
