---
--- Generated by Luanalysis
--- Created by lyrthras.
--- DateTime: 24/08/2021 1:40 AM
---

--- Liquid items
---@class LiqItem : Item
---@field liquid string

local base = require "readers.item".read

local function read(path, json)
  ---@type LiqItem
  local item = base(path, json)

  item.liquid = json.liquid

  return item
end

return {read = read}
