---
--- Generated by Luanalysis
--- Created by lyrthras.
--- DateTime: 23/08/2021 6:56 PM
---

--- Material items
---@class MatItem : Item
---@field materialId number

local base = require "readers.item".read

local function read(path, json)
  ---@type MatItem
  local item = base(path, json)

  item.materialId = json.materialId

  return item
end

return {read = read}
