---
--- Generated by Luanalysis
--- Created by lyrthras.
--- DateTime: 23/08/2021 10:13 PM
---

--- Objects
---@class Object : Item
---@field colonyTags string[]
---@field race string
---@field printable boolean
---@field scannable boolean
---@field health number|nil
---@field objectType string|nil   @ "container" for containers
---@field slotCount number|nil    @ implied by "container"
-- anchors?
-- maxUpgradeStage
-- upgradeStages TODO
-- merchant stuff TODO

local base = require "readers.item".read

local function read(path, json)
  ---@type Object
  local item = base(path, json)

  item.id = json.objectName
  item.colonyTags = json.colonyTags or {}
  item.race = json.race or "generic"
  item.printable = (json.printable == nil and true) or json.printable
  item.scannable = (json.scannable == nil and true) or json.scannable
  item.health = json.health
  item.objectType = json.objectType
  item.slotCount = json.slotCount

  return item
end

return {read = read}
