---
--- Generated by Luanalysis
--- Created by lyrthras.
--- DateTime: 24/08/2021 3:12 AM
---

--- Tools
---@class Tool : Item
---@field twoHanded boolean

local base = require "readers.item".read

local function read(path, json)
  ---@type Tool
  local item = base(path, json)

  item.twoHanded = json.twoHanded or false

  return item
end

return {read = read}
