---
--- Generated by Luanalysis
--- Created by lyrthras.
--- DateTime: 24/08/2021 2:05 AM
---

--- Wearables
---@class Wear : Item
---@field tier number
-- TODO effects

local base = require "readers.item".read

local function read(path, json)
  ---@type Wear
  local item = base(path, json)

  item.tier = json.level

  -- TODO stats

  return item
end

return {read = read}
