---
--- Generated by Luanalysis
--- Created by lyrthras.
--- DateTime: 23/08/2021 5:35 PM
---

local log = {
  _TEMPLATE = ""
}

function log.warn(...)
  io.write("Warning: ") print(string.format(...))
end

function log.error(...)
  io.write("ERROR: ") print(string.format(...))
end

function log.setProgressTemplate(tpl)
  log._TEMPLATE = tpl
end

function log.updateProgress(...)
  io.write(string.format(log._TEMPLATE .. "\r", ...))
end

return log