---
--- Generated by Luanalysis
--- Created by lyrthras.
--- DateTime: 29/10/2021 9:55 PM
---

-- Look in lib/ directory
package.path = package.path .. ";./lib/?/init.lua"


-- Allows relative requires (last resort), and requiring
-- directories will require init.lua in them if present

local _require = require
require = function(modname)
  local prefix = (debug.getinfo(2).source:match("@(.+)[\\/]"):gsub("[\\/]+","/"))
  local origPath = package.path
  package.path = package.path .. ";"..prefix.."/?/init.lua;"..prefix.."/?.lua"

  local try = function(success, ...)
    package.path = origPath
    if success then
      return ...
    else
      error(select(2, ...))
    end
  end

  return try(pcall(_require, modname))
end

