---
--- Generated by Luanalysis
--- Created by lyrthras.
--- DateTime: 23/08/2021 7:03 PM
---

--- Generic items
---@class Item : DbEntry
---@field origin string       @ File path
---@field name string
---@field desc string
---@field category string     @ mappable
---@field maxStack number
---@field itemTags string[]
---@field teaches string[]
---@field icon string|table   @ process
---@field image string|table  @ process
---@field price number
---@field rarity string|nil
---@field apexDesc string|nil
---@field avianDesc string|nil
---@field floranDesc string|nil
---@field glitchDesc string|nil
---@field humanDesc string|nil
---@field hylotlDesc string|nil
---@field novakidDesc string|nil

local function read(path, json)
  ---@type Item
  local item = {
    origin = path,
    id = json.itemName,
    name = json.shortdescription,
    desc = json.description,
    category = json.category,
    rarity = json.rarity,
    icon = json.inventoryIcon,    -- TODO process icon - do on process stage
    price = json.price or 0,
    maxStack = json.maxStack or 1,
    teaches = json.learnBlueprintsOnPickup or {},
    itemTags = json.itemTags or {},
    image = json.largeImage or json.image or json.inventoryIcon,

    apexDesc = json.apexDescription,
    avianDesc = json.avianDescription,
    floranDesc = json.floranDescription,
    glitchDesc = json.glitchDescription,
    humanDesc = json.humanDescription,
    hylotlDesc = json.hylotlDescription,
    novakidDesc = json.novakidDescription,
  }

  -- TODO color mappings (armor) - colorOptions - pass to icon

  return item
end

return {read = read}
