---
--- Generated by Luanalysis
--- Created by lyrthras.
--- DateTime: 02/10/2021 4:21 PM
---

--- .dungeon files containing parts
---@class Dungeon : DbEntry
---@field origin string
---@field parts table<string,string>  @ [part id, file]

local log = require "log"

local function read(path, json)
  ---@type Dungeon
  local dungeon = {
    origin = path,
    id = json.name,
    parts = {}
  }

  for _, part in ipairs(json.parts) do
    if part.def[1] == "tmx" then
      dungeon.parts[part.name] = part.def[2]
    else
      log.warn("map type %s not supported (yet)", part.def[1])
    end
  end

  return dungeon
end

return {read = read}
