---
--- Generated by Luanalysis
--- Created by lyrthras.
--- DateTime: 23/08/2021 5:11 PM
---

---@class DbEntry
---@field id  string    @ the string name (id) of the entry


-- reader contains a function read(jsonFilePath, json),
-- json is a lua table already
-- returns table db

-- readerPath | { readerPath [, databaseName [, keyNameProvider]] }
-- databaseName = databaseName or readerPath:match("[^.]+")
-- keyNameProvider = keyNameProvider(fileName, resultObject, keyCaptures:table) or key
-- todo fill
local extReaders = {
  dungeon = "dungeon",
  treasurepools = "pools",
  matitem = "item.matitem"
}

local wcReaders = {
  ["/aa/bb/**.json"] = "prefix.aa",
  ["/terrestrial_worlds.config.patch"] = { "aaaaaaa", "planets" }
}

local t = {}

for ext,reader in pairs(extReaders) do
  ext = ".+%."..ext:gsub("%p","%%%1").."$"
  t[ext] = require("readers." .. reader)
end

for pat,reader in pairs(wcReaders) do
  pat = "^" .. pat
      :gsub("%*%*","\2"):gsub("%*","\3")
      :gsub("%p","%%%1")
      :gsub("\2",".*"):gsub("\3","[^/]*") .. "$"
  t[pat] = require("readers." .. reader)
end


return t
