---
--- Generated by Luanalysis
--- Created by lyrthras.
--- DateTime: 02/10/2021 3:07 PM
---

---@shape ItemDescriptor
---@field item string
---@field count number
---@field parameters nil|table

--- Recipes
---@class Recipe
---@field input ItemDescriptor[]
---@field output ItemDescriptor
---@field groups string[]

local function read(path, json)
  ---@type Recipe
  local recipe = {
    input = json.input,
    output = json.output,
    groups = json.groups,
  }

  if type(json.currencyInputs) == "table" then
    for item, count in pairs(json.currencyInputs) do
      recipe.input[#recipe.input+1] = { item = item, count = count }
    end
  end

  return recipe
end

return {read = read}
