---
--- Generated by Luanalysis
--- Created by lyrthras.
--- DateTime: 04/10/2021 5:26 PM
---

---@shape TileDef
---@field id string
---@field type "object"|"liquid"|"material"|"none"

--- Tilesets, just for reference
---@class Tileset
---@field tiles table<number,TileDef>

local function read(path, json)
  ---@type Tileset
  local tileset = {
    tiles = {}
  }

  for offset, prop in pairs(json.tileproperties) do
    if prop.material then
      tileset.tiles[tonumber(offset)] = { id = prop.material, type = "material" }
    elseif prop.object then
      tileset.tiles[tonumber(offset)] = { id = prop.object, type = "object" }
    elseif prop.liquid then
      tileset.tiles[tonumber(offset)] = { id = prop.liquid, type = "liquid" }
    end
  end

  return tileset
end

return {read = read}
