---
--- Generated by Luanalysis
--- Created by lyrthras.
--- DateTime: 02/10/2021 4:24 PM
---


local function parse(db, path, json)

end






package.path = package.path .. ";./lib/?/init.lua"
sha = require "sha"
zlib = require "zzlib"
data = "eJzt2VEOgjAQBNCehZtxDQXldvzplbQfm9RaIth2d9mdSSamCZi+tMFI1xCWFUVRFEVRFEXRpg3K48G4FS/OPJ6sFE9WCrx2rRR4bceTlQKv7cBrO/DaDry2A6/twCuX2/D52SNavNGYenuZNXnvSa16aS0vhfZYZ6n/wNPwbR2T5uapgVvy/cac7d9fnU/ujYnrt2R7eGvcItLvKDm9Wt4/k2fMfOm4RbScMXB4NZ0h9fZqOyeMnmvS0vifHHVy2Zfsd6c05jRSH+/v4+6z0D33ndFaW09Wb14P+5nm2fKZpdne2qnZ3NOqzc1llTZzO2vMe+8rXSfpPOrfe730/GvM0vNA/fUF3P0/mg=="
out = zlib.inflate(sha.base642bin(data))
for i = 1,14400,4 do
  io.write(string.format("[%s,%s,%s,%s]",string.byte(out:sub(i,i)), string.byte(out:sub(i+1,i+1)), string.byte(out:sub(i+2,i+2)), string.byte(out:sub(i+3,i+3))))
  if (i+3)%60 == 0 then io.write("//\n") end
end
out:byte(i) -- get byte at pos


return {}
